/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    // "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "ap-southeast-2_aQI4gQM93",
    "aws_user_pools_web_client_id": "55tavo3m8a6ch2lh46o91pchp",
    "oauth": {
        "domain": "become.auth.ap-southeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn":  "https://cognitopoc.z8.web.core.windows.net/landing/",
        "redirectSignOut": "https://cognitopoc.z8.web.core.windows.net",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"

};



export default awsmobile;
